# Generated by Django 5.1.3 on 2024-11-26 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='actor_image',
            field=models.ImageField(blank=True, null=True, upload_to='actor_image/'),
        ),
        migrations.AlterField(
            model_name='director',
            name='director_image',
            field=models.ImageField(blank=True, null=True, upload_to='director_image'),
        ),
        migrations.AlterField(
            model_name='moments',
            name='movie_moments',
            field=models.ImageField(blank=True, null=True, upload_to='  movie_moments/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_image',
            field=models.ImageField(blank=True, null=True, upload_to='movie_image/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_trailer',
            field=models.FileField(blank=True, null=True, upload_to='movie_trailer/'),
        ),
        migrations.AlterField(
            model_name='movielanguages',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_languages', to='movie_app.movie'),
        ),
        migrations.AlterField(
            model_name='movielanguages',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='movie_languages'),
        ),
    ]
